name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version --no-git-tag-version $VERSION
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}